site_name: neuromorphopy
repo_url: https://github.com/kpeez/neuromorphopy
site_url: https://kpeez.github.io/neuromorphopy
site_description: Lightweight python package for downloading neuron morphologies from the NeuroMorpho archive.
site_author: Kyle Puhger

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - User Guide:
      - Installation: user_guide/installation.md
      - Basic Usage: user_guide/basic_usage.md
      - Building Queries: user_guide/queries.md
      - Downloading Data: user_guide/downloading.md
  - API Reference:
      - Client: api_reference/client.md
      - NeuroMorpho Queries: api_reference/query.md
      - Utilities: api_reference/utils.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
  - include-markdown

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kpeez/neuromorphopy
