[project]
name = "neuromorphopy"
version = "0.3.3"
requires-python = ">=3.11"
description = "Lightweight standalone python CLI tool for downloading neuron morphologies from the NeuroMorpho archives."
authors = [{ name = "Kyle Puhger", email = "krpuhger@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
keywords = ["neuroscience", "morphology", "neurons", "neuromorpho"]
dependencies = [
    "httpx>=0.28.1",
    "pandas>=2.2.3",
    "pydantic>=2.11.3",
    "pyyaml>=6.0.2",
    "tqdm>=4.67.1",
    "typer>=0.15.2",
]

[dependency-groups]
dev = [
    "pandas-stubs>=2.2.3.250308",
    "prek>=0.4.11",
    "pytest-asyncio>=0.23.5",
    "pytest-mock>=3.12.0",
    "ruff>=0.16.0",
    "ty>=0.0.63",
]
docs = [
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings[python]",
  "mkdocs-include-markdown-plugin>=7.0.0",
  "pymdown-extensions>=10.12",
]

[project.scripts]
neuromorpho = "neuromorphopy.cli:main"

[project.urls]
repository = "https://github.com/kpeez/neuromorphopy"
documentation = "https://neuromorphopy.readthedocs.io/en/latest/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--log-cli-level=INFO -sv --durations=0"

[tool.uv]
default-groups = ["dev", "docs"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ty.environment]
python-version = "3.11"

[tool.ty.src]
include = ["neuromorphopy"]
